services:
  db:
    image: postgres:17
    ports:
      - "5446:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: db_name
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo

    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
